CREATE TYPE transaction_type AS ENUM ('entrada', 'saida');

CREATE TABLE transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description TEXT NOT NULL,
  amount NUMERIC(10, 2) NOT NULL,
  type transaction_type NOT NULL,
  transaction_date DATE NOT NULL,
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL, -- Link para a tabela de categorias
  created_at TIMESTAMPTZ DEFAULT NOW()
);